from decimal import Decimal
from typing import Protocol
from bestbox.core.domain.inventory import ProductStock, InventoryLot


class InventoryRepositoryProtocol(Protocol):
    def get_product_stock(self, product_id: int) -> ProductStock | None: ...
    def get_product_stock_by_part_number(self, part_number: str) -> ProductStock | None: ...
    def list_low_stock(self, threshold: Decimal) -> list[ProductStock]: ...
    def list_lots(self, product_id: int) -> list[InventoryLot]: ...
